stages:
  - vet
  - deps
  - test
  - test-race

variables:
  GOPATH: "$CI_PROJECT_DIR/.go"
  GOMODCACHE: "$CI_PROJECT_DIR/.go/pkg/mod"
  GOTOOLCHAIN: local

cache:
  key:
    files:
      - go.sum
  paths:
    - .go/pkg/mod/

default:
  image: golang:1.25
  tags:
    - linux

vet:
  stage: vet
  script:
    - make vet

deps:
  stage: deps
  script:
    - make deps

test:
  stage: test
  script:
    - make test

test-race:
  stage: test-race
  script:
    - make test-race
