// Package cert handles SSH certificate building and signing.
package cert

import (
	"context"
	"crypto/rand"
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"net"
	"regexp"
	"sort"
	"strings"
	"time"

	"golang.org/x/crypto/ssh"

	"github.com/FtlC-ian/gobless/internal/errs"
	"github.com/FtlC-ian/gobless/internal/signer"
)

// CertType represents user or host cert.
type CertType uint32

const (
	UserCert CertType = CertType(ssh.UserCert)
	HostCert CertType = CertType(ssh.HostCert)
)

// defaultExtensions are the OpenSSH default user cert extensions.
var defaultExtensions = map[string]string{
	"permit-pty":              "",
	"permit-port-forwarding":  "",
	"permit-agent-forwarding": "",
	"permit-X11-forwarding":   "",
	"permit-user-rc":          "",
}

// Request is the validated input for a signing operation.
type Request struct {
	CertType      CertType
	PublicKey     ssh.PublicKey // already parsed
	Principals    []string      // validated, non-empty
	TTL           time.Duration
	SourceAddress string            // optional CIDR, goes into critical options
	ForceCommand  string            // optional, goes into critical options
	Extensions    map[string]string // nil = use defaults
	KeyID         string            // generated by caller, logged by sshd
}

// Response wraps the signed cert.
type Response struct {
	Certificate *ssh.Certificate
	// Marshaled authorized-keys line, ready to write
	AuthorizedKey string
}

// Sign builds and signs an SSH certificate using the provided signer.
// It validates the request fields, constructs the certificate, and signs it.
func Sign(ctx context.Context, req *Request, s signer.Signer) (*Response, error) {
	// Validate
	if len(req.Principals) == 0 {
		return nil, fmt.Errorf("cert: principals must not be empty")
	}
	if req.TTL <= 0 {
		return nil, fmt.Errorf("cert: TTL must be positive, got %v", req.TTL)
	}
	if req.CertType != UserCert && req.CertType != HostCert {
		return nil, fmt.Errorf("cert: unknown cert type %d", req.CertType)
	}

	// Reject RSA keys below 2048 bits.
	if err := checkRSAKeySize(req.PublicKey); err != nil {
		return nil, err
	}

	// Generate non-zero random serial.
	serial, err := randomSerial()
	if err != nil {
		return nil, fmt.Errorf("cert: generate serial: %w", err)
	}

	// Build extensions map.
	// Host certs must have NO extensions (BLESS compatible); user certs default to
	// the standard five permit-* extensions when none are explicitly provided.
	//
	// Enforce at the cert layer: host certs always get zero extensions, regardless
	// of what the caller passes. Non-empty Extensions on a host cert request is a
	// misconfiguration/caller error; silently enforcing correct behavior is safer
	// and more operator-friendly than returning an error.
	var exts map[string]string
	if req.CertType == HostCert {
		// OpenSSH spec and BLESS compatibility both require host certs to carry no
		// extensions. Ignore any caller-supplied value unconditionally.
		exts = map[string]string{}
	} else if req.Extensions == nil {
		exts = copyMap(defaultExtensions)
	} else {
		exts = req.Extensions
	}

	// Sort extensions keys to produce lexicographic ordering in the cert wire format.
	sortedExtKeys := sortedKeys(exts)
	orderedExts := make(map[string]string, len(exts))
	for _, k := range sortedExtKeys {
		orderedExts[k] = exts[k]
	}

	// Build critical options.
	critOpts := make(map[string]string)
	if req.SourceAddress != "" {
		// Validate each comma-separated CIDR before encoding into the cert.
		for _, cidr := range strings.Split(req.SourceAddress, ",") {
			cidr = strings.TrimSpace(cidr)
			if _, _, err := net.ParseCIDR(cidr); err != nil {
				return nil, fmt.Errorf("cert: invalid source-address CIDR %q: %w",
					cidr, errs.Wrap(errs.ErrInvalidRequest, err.Error()))
			}
		}
		critOpts["source-address"] = req.SourceAddress
	}
	if req.ForceCommand != "" {
		critOpts["force-command"] = req.ForceCommand
	}

	now := time.Now()
	validAfter := uint64(now.Unix())
	validBefore := validAfter + uint64(req.TTL.Seconds())

	cert := &ssh.Certificate{
		Serial:          serial,
		CertType:        uint32(req.CertType),
		Key:             req.PublicKey,
		KeyId:           req.KeyID,
		ValidPrincipals: req.Principals,
		ValidAfter:      validAfter,
		ValidBefore:     validBefore,
		Permissions: ssh.Permissions{
			CriticalOptions: critOpts,
			Extensions:      orderedExts,
		},
	}

	signed, err := s.Sign(cert)
	if err != nil {
		return nil, fmt.Errorf("cert: sign: %w", err)
	}
	if signed == nil {
		return nil, fmt.Errorf("cert: signer returned nil certificate without error")
	}

	authKey := string(ssh.MarshalAuthorizedKey(signed))

	return &Response{
		Certificate:   signed,
		AuthorizedKey: authKey,
	}, nil
}

// unsafeKeyIDChars matches characters not allowed in a KeyID principal segment.
var unsafeKeyIDChars = regexp.MustCompile(`[^a-zA-Z0-9._@-]`)

// GenerateKeyID produces a KeyID string for audit traceability.
// Format: gobless-<cert-type>-<sanitized-principal[0]>-<unix-timestamp>-<random-hex-8>
// principals[0] is sanitized: characters outside [a-zA-Z0-9._@-] are replaced with '_'.
func GenerateKeyID(certType CertType, principals []string) (string, error) {
	if len(principals) == 0 {
		return "", fmt.Errorf("cert: principals required for key ID generation")
	}
	rb := make([]byte, 4)
	if _, err := rand.Read(rb); err != nil {
		return "", fmt.Errorf("cert: generate key id random: %w", err)
	}
	typeName := "user"
	if certType == HostCert {
		typeName = "host"
	}
	sanitized := unsafeKeyIDChars.ReplaceAllString(principals[0], "_")
	return fmt.Sprintf("gobless-%s-%s-%d-%s",
		typeName, sanitized, time.Now().Unix(), hex.EncodeToString(rb)), nil
}

// randomSerial generates a non-zero random uint64.
func randomSerial() (uint64, error) {
	for {
		b := make([]byte, 8)
		if _, err := rand.Read(b); err != nil {
			return 0, err
		}
		n := binary.BigEndian.Uint64(b)
		if n != 0 {
			return n, nil
		}
	}
}

func copyMap(m map[string]string) map[string]string {
	out := make(map[string]string, len(m))
	for k, v := range m {
		out[k] = v
	}
	return out
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// checkRSAKeySize rejects RSA public keys below 2048 bits.
func checkRSAKeySize(pub ssh.PublicKey) error {
	if !strings.HasPrefix(pub.Type(), "ssh-rsa") {
		return nil
	}
	wire := pub.Marshal()
	bits := rsaModulusBitsFromWire(wire)
	if bits > 0 && bits < 2048 {
		return fmt.Errorf("cert: RSA key must be at least 2048 bits, got %d", bits)
	}
	return nil
}

// rsaModulusBitsFromWire parses the bit-length of the RSA modulus from the
// SSH wire encoding of an RSA public key.
func rsaModulusBitsFromWire(wire []byte) int {
	// Wire format: length-prefixed strings/mpints
	// Skip "ssh-rsa" string field: 4-byte length + content
	if len(wire) < 4 {
		return 0
	}
	nameLen := int(wire[0])<<24 | int(wire[1])<<16 | int(wire[2])<<8 | int(wire[3])
	if len(wire) < 4+nameLen+4 {
		return 0
	}
	// Skip past name and the exponent mpint
	off := 4 + nameLen
	// exponent length
	eLen := int(wire[off])<<24 | int(wire[off+1])<<16 | int(wire[off+2])<<8 | int(wire[off+3])
	off += 4 + eLen
	if len(wire) < off+4 {
		return 0
	}
	// modulus length
	nLen := int(wire[off])<<24 | int(wire[off+1])<<16 | int(wire[off+2])<<8 | int(wire[off+3])
	off += 4
	if len(wire) < off+nLen {
		return 0
	}
	nBytes := wire[off : off+nLen]
	// leading zero byte is used for sign in mpint encoding
	if len(nBytes) > 0 && nBytes[0] == 0 {
		nBytes = nBytes[1:]
	}
	if len(nBytes) == 0 {
		return 0
	}
	// bit length = (len-1)*8 + bits in top byte
	topByte := nBytes[0]
	topBits := 0
	for topByte > 0 {
		topBits++
		topByte >>= 1
	}
	return (len(nBytes)-1)*8 + topBits
}
